### ISSUE TITLE
Editable content

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked.eu#10]
I guess for now, we should use a duplicate of the content in the existing ORG folder system. 

If you can let me know where the EU content is linked to I will start editing it.

**Comment by dantheta** [comment]
I've duplicated a set of pages from the UK site into a feed-eu folder under browse.blocked in ModX.  I'll hook up the frontend shortly.  Clearing the cache in the frontend control panel clears content for both sites.

**Comment by dantheta** [comment]
Editable content is now all hooked up.  The EU versions of the page content are under feed-eu.  I've added a tiny difference to the introductory text for legal-pages to check that it's working.
