### ISSUE TITLE
About page not updating

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked.eu#20]
I've cleared the cache but content I've added to /about hasn't appeared. 

Other content is removed tho.

**Comment by dantheta** [comment]
I'll check it in the control panel in a short while, but it's worth checking that the document type is XML, and that is using one of the 1x3 or 2x3 templates. It also needs to be under the feed-eu resource.

**Comment by JimKillock** [comment]
Thanks Dan, template is BlockedContent1x3 and XML, content is here: https://browse.blocked.org.uk/feed-eu/about-page.xml

**Comment by dantheta** [comment]
The resource alias on CMS pages needs to be the same as the slug used on the frontend: blocked.eu/about -> feed-eu/about.xml.  I've changed the resource alias and it's loaded now.
