### ISSUE TITLE
Remove "stay in touch" block

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked.eu#21]
This can be removed, then we're pretty much done with the basic content strip back.

**Comment by JimKillock** [comment]
I've stripped out the block from the feed: https://browse.blocked.org.uk/feed-eu/chunks.xml 

but it is still appearing on netblocked.eu (I have also cleared the cache on blocked.org.uk )

**Comment by dantheta** [comment]
The form hosted in ModX was hastily deprecated because it couldn't POST data into the campaign CMS.  I've disabled it in the frontend code.
