### ISSUE TITLE
support page feed not working

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked.eu#22]
For some reason the support page feed doesn't seem to be showing on the netblocked.eu support page content

https://www.netblocked.eu/support

https://browse.blocked.org.uk/feed-eu/support-page.xml

**Comment by dantheta** [comment]
It's the resource name - the resource alias needs to be "support", not "support-page".

https://browse.blocked.org.uk/feed-eu/support.xml

**Comment by dantheta** [comment]
I've changed the resource name and cleared the cache.
