### ISSUE TITLE
Create basic minimal version

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked.eu#3]
Use features already generated at blocked.org.uk

**Comment by dantheta** [comment]
I've got an initial version of the python frontend with the legal-blocks page.  I just need GH permissions to push to the blocked.eu repo, if that's OK (or I can do merge request)

**Comment by JimKillock** [comment]
Thanks, hopefully that's all set correctly now

**Comment by dantheta** [comment]
The basic version is up and running at https://www.netblocked.eu.  It has the legal blocks page and the ability to submit new sites.  The theme is a fork of the UK version; they can be modified independently but can still share code.

**Comment by JimKillock** [comment]
Thanks Dan, should I start raising tickets for the things we want to change / adapt?

**Comment by dantheta** [comment]
Yep, sounds good.
