### ISSUE TITLE
Auto-generate 451 Unavailable pages

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked.eu#7]
Create 451 Unavailable pages from the database per court order.

Host these at 
uk.451unavailable.org/url.tld
de.451unavailable.org/url.tld

etc

**Comment by JimKillock** [comment]
This will naturally follow the changes to add court order and court judgment information in the blocked.org.uk tickets. That information will be needed to auto-generate 451 pages

**Comment by JimKillock** [comment]
@dantheta when we get to this, you'll need the domains pointing – Lee could do that tomorrow (Tuesday) if you like. I'll email you both.

**Comment by dantheta** [comment]
Do we want these pages to use a similar theme to the main 451unavailable site?

**Comment by JimKillock** [comment]
They could use the 451 logo and typography but they could also be unbranded. I'd had unbranded in my mind but I'm open to suggestions. Here is the unbranded example:

https://www.451unavailable.org/what-is-error-451/example-error-451-page

**Comment by dantheta** [comment]
There's a demo here: https://uk.451unavailable.org/http://couchtuner.bz

There were some placeholders in the template that we don't currently have in the data model - we can add those in as editable fields, or we can drop them from the template.

**Comment by JimKillock** [comment]
Thanks Dan, looking good. Comments:

(1) We would generate the 451 notice per ISP, so we may need to that data to the admin back end. The individual ISP name would replace "BT, Sky, TalkTalk and VirginMedia", so "restricted at TT".
(2) [Court Order Expiration Date] can default to "further notice".
(3) Active links to documents of course :)
(4) We may need a field for the name of the website / service … or we could edit / standardise those we are using in the backend.

**Comment by dantheta** [comment]
I've added an extra URL format that prefixes the ISP onto the front.

https://uk.451unavailable.org/http://www.afdah.tv shows the multi-ISP version

https://uk.451unavailable.org/BT/http://www.afdah.tv shows the single ISP.

I was thinking that the multi-isp version could detect the visitors ISP and show only that version (with the explicit ISP as a bookmarkable URL), and fall back on the multi-isp version if the visitor is not from one of the blocking networks.

Legislation link is active, others to follow.

**Comment by JimKillock** [comment]
The way we will use the pages is to link to the example blocking page on the ISP blocking results; so the BT result would link to an example error 451 for BT; the Virgin result to a Virgin example etc.

The purpose is to show the ISPs (and people browsing the blocked website) how the ISP blocking pages should look, if that makes sense. So I am not sure if there is value in detecting the visitor IP address and network. I could be missing something of course!

**Comment by dantheta** [comment]
That sounds fine :)

Updated with links to judgments/orders.

**Comment by JimKillock** [comment]
I've made a few changes to the example page language: 

https://www.451unavailable.org/what-is-error-451/example-error-451-page

Could you amend the text as per the changes to the example?

**Comment by dantheta** [comment]
Yep, that's updated.  There are still a couple of field placeholders in the template that we don't have in the data model - we might want to fill out the information we keep for the legal authorities, and add a field for the court order expiry date.

**Comment by dantheta** [comment]
Also there's a contact address placeholder for the organisation that obtained the injunction.  I can add a field for that, and conditionally display that part of the sentence when the field is filled in.

**Comment by dantheta** [comment]
I've added the extra fields, and made the sentence flows conditional where they aren't filled in.

**Comment by JimKillock** [comment]
I think we should make this active soon and build it into the front page. It will take a while to get the paperwork.

**Comment by dantheta** [comment]
Now linked from a list on the site results page.

**Comment by dantheta** [comment]
Linked in the results table.

The list of networks in the footer panel comes from the ISPs associated with the court order in the backend.
