### ISSUE TITLE
Status page

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked.eu#8]
Amend server status page to list EU tests only.

For UK, this should include the networks affected by copyright blocks only.

Server status page table should give 
* name of the network,
* link to their home page,
* name of the country in English

It should sort by country

**Comment by JimKillock** [comment]
Dan, to help me get the probes sorted, this would be the thing to do next.

**Comment by dantheta** [comment]
I've fixed up the probe data so far for the EU probes, so that their names and locations are listed.

**Comment by dantheta** [comment]
We can change the names of the ISPS easily - it's defaulted to the network names we get from IP WHOIS.

**Comment by dantheta** [comment]
Country name and sort order added.

**Comment by dantheta** [comment]
Owner links added.
